### ISSUE TITLE
Proper landing page

### ISSUE THREAD

**Issue by clemsos** [topogram/topogram.github.io#12]
Topogram needs a proper landing page 

- [x] Move docs to `/docs` #13 
- [x] Fancy header
- [ ] Needs a funny logo / image / character #9
- [x] Introduce the main 3-5 features
- [ ] Explain why Topogram is used (#description)
- [ ] Showcase of 5 existing (good) examples
- [x] Link to app
- [x] Link to Read the docs / get started
- [x] Partners (with logo)  see #10
- [x] News / links / papers about the project - #8
- [ ] Call to action : register newsletter ? 
- [ ]  Support with list of challenges - #14 
- [x] Email
- [x] Twitter
- [x] Github
